//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.27 at 10:38:29 AM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActionEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="ADD"/&gt;
 *     &lt;enumeration value="EXECUTE"/&gt;
 *     &lt;enumeration value="DELETE"/&gt;
 *     &lt;enumeration value="MODIFY"/&gt;
 *     &lt;enumeration value="PATCH"/&gt;
 *     &lt;enumeration value="READ"/&gt;
 *     &lt;enumeration value="REQUEST"/&gt;
 *     &lt;enumeration value="RESPONSE"/&gt;
 *     &lt;enumeration value="GRANT"/&gt;
 *     &lt;enumeration value="DENY"/&gt;
 *     &lt;enumeration value="REJECT"/&gt;
 *     &lt;enumeration value="APPROVE"/&gt;
 *     &lt;enumeration value="AUTHENTICATE"/&gt;
 *     &lt;enumeration value="AUTHORIZE"/&gt;
 *     &lt;enumeration value="CLOSE"/&gt;
 *     &lt;enumeration value="OPEN"/&gt;
 *     &lt;enumeration value="REOPEN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ActionEnumType", namespace = "http://www.cote.org/accountmanager/objects/types")
@XmlEnum
public enum ActionEnumType {

    UNKNOWN,
    ADD,
    EXECUTE,
    DELETE,
    MODIFY,
    PATCH,
    READ,
    REQUEST,
    RESPONSE,
    GRANT,
    DENY,
    REJECT,
    APPROVE,
    AUTHENTICATE,
    AUTHORIZE,
    CLOSE,
    OPEN,
    REOPEN,
    VECTORIZE
    ;

    public String value() {
        return name();
    }

    public static ActionEnumType fromValue(String v) {
        return valueOf(v);
    }

}
