//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.22 at 05:13:20 PM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlignmentEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AlignmentEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="LAWFULGOOD"/&gt;
 *     &lt;enumeration value="NEUTRALGOOD"/&gt;
 *     &lt;enumeration value="CHAOTICGOOD"/&gt;
 *     &lt;enumeration value="LAWFULNEUTRAL"/&gt;
 *     &lt;enumeration value="NEUTRAL"/&gt;
 *     &lt;enumeration value="CHAOTICNEUTRAL"/&gt;
 *     &lt;enumeration value="LAWFULEVIL"/&gt;
 *     &lt;enumeration value="NEUTRALEVIL"/&gt;
 *     &lt;enumeration value="CHAOTICEVIL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AlignmentEnumType", namespace = "http://www.cote.org/propellant/objects/types")
@XmlEnum
public enum AlignmentEnumType {

    UNKNOWN,
    LAWFULGOOD,
    NEUTRALGOOD,
    CHAOTICGOOD,
    LAWFULNEUTRAL,
    NEUTRAL,
    CHAOTICNEUTRAL,
    LAWFULEVIL,
    NEUTRALEVIL,
    CHAOTICEVIL;

    public String value() {
        return name();
    }

    public static AlignmentEnumType fromValue(String v) {
        return valueOf(v);
    }

}
