//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.27 at 10:38:29 AM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComparatorEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComparatorEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="ANY"/&gt;
 *     &lt;enumeration value="NOT_ANY"/&gt;
 *     &lt;enumeration value="EQUALS"/&gt;
 *     &lt;enumeration value="NOT_EQUALS"/&gt;
 *     &lt;enumeration value="BETWEEN"/&gt;
 *     &lt;enumeration value="LESS_THAN"/&gt;
 *     &lt;enumeration value="LESS_THAN_OR_EQUALS"/&gt;
 *     &lt;enumeration value="GREATER_THAN"/&gt;
 *     &lt;enumeration value="GREATER_THAN_OR_EQUALS"/&gt;
 *     &lt;enumeration value="NOT_IN"/&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="NOT_NULL"/&gt;
 *     &lt;enumeration value="IS_NULL"/&gt;
 *     &lt;enumeration value="IS_NULL_EQUALS"/&gt;
 *     &lt;enumeration value="IS_NULL_NOT_EQUALS"/&gt;
 *     &lt;enumeration value="LIKE"/&gt;
 *     &lt;enumeration value="GROUP_AND"/&gt;
 *     &lt;enumeration value="GROUP_OR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ComparatorEnumType", namespace = "http://www.cote.org/accountmanager/objects/types")
@XmlEnum
public enum ComparatorEnumType {

    UNKNOWN,
    ANY,
    NOT_ANY,
    EQUALS,
    NOT_EQUALS,
    BETWEEN,
    LESS_THAN,
    LESS_THAN_OR_EQUALS,
    GREATER_THAN,
    GREATER_THAN_OR_EQUALS,
    NOT_IN,
    IN,
    NOT_NULL,
    IS_NULL,
    IS_NULL_EQUALS,
    IS_NULL_NOT_EQUALS,
    LIKE,
    ILIKE,
    GROUP_AND,
    GROUP_OR;

    public String value() {
        return name();
    }

    public static ComparatorEnumType fromValue(String v) {
        return valueOf(v);
    }

}
