//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.27 at 10:38:29 AM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactInformationEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContactInformationEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="INDIVIDUAL"/&gt;
 *     &lt;enumeration value="GROUP"/&gt;
 *     &lt;enumeration value="ORGANIZATION"/&gt;
 *     &lt;enumeration value="COMPANY"/&gt;
 *     &lt;enumeration value="ACCOUNT"/&gt;
 *     &lt;enumeration value="USER"/&gt;
 *     &lt;enumeration value="PERSON"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ContactInformationEnumType", namespace = "http://www.cote.org/accountmanager/objects/types")
@XmlEnum
public enum ContactInformationEnumType {

    UNKNOWN,
    INDIVIDUAL,
    GROUP,
    ORGANIZATION,
    COMPANY,
    ACCOUNT,
    USER,
    PERSON;

    public String value() {
        return name();
    }

    public static ContactInformationEnumType fromValue(String v) {
        return valueOf(v);
    }

}
