//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.26 at 09:29:53 PM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CredentialEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CredentialEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="LEGACY_PASSWORD"/&gt;
 *     &lt;enumeration value="HASHED_PASSWORD"/&gt;
 *     &lt;enumeration value="SALT"/&gt;
 *     &lt;enumeration value="ENCRYPTED_PASSWORD"/&gt;
 *     &lt;enumeration value="ENCRYPTED_IDENTITY"/&gt;
 *     &lt;enumeration value="TOKEN"/&gt;
 *     &lt;enumeration value="CERTIFICATE"/&gt;
 *     &lt;enumeration value="SIGNATURE"/&gt;
 *     &lt;enumeration value="SESSION"/&gt;
 *     &lt;enumeration value="KEY"/&gt;
 *     &lt;enumeration value="KNOWLEDGE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CredentialEnumType")
@XmlEnum
public enum CredentialEnumType {

    UNKNOWN,
    LEGACY_PASSWORD,
    HASHED_PASSWORD,
    SALT,
    ENCRYPTED_PASSWORD,
    ENCRYPTED_IDENTITY,
    TOKEN,
    CERTIFICATE,
    SIGNATURE,
    SESSION,
    KEY,
    KNOWLEDGE;

    public String value() {
        return name();
    }

    public static CredentialEnumType fromValue(String v) {
        return valueOf(v);
    }

}
