//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.26 at 09:04:07 AM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="INCEPT"/&gt;
 *     &lt;enumeration value="GRADUATE"/&gt;
 *     &lt;enumeration value="CONCLUDE"/&gt;
 *     &lt;enumeration value="INGRESS"/&gt;
 *     &lt;enumeration value="MOVE"/&gt;
 *     &lt;enumeration value="CONSTRUCT"/&gt;
 *     &lt;enumeration value="DESTRUCT"/&gt;
 *     &lt;enumeration value="OPERATE"/&gt;
 *     &lt;enumeration value="STABLIZE"/&gt;
 *     &lt;enumeration value="DESTABILIZE"/&gt;
 *     &lt;enumeration value="TRANSFER"/&gt;
 *     &lt;enumeration value="EGRESS"/&gt;
 *     &lt;enumeration value="IMMIGRATE"/&gt;
 *     &lt;enumeration value="EMIGRATE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EventEnumType", namespace = "http://www.cote.org/propellant/objects/types")
@XmlEnum
public enum EventEnumType {

    UNKNOWN,
    OBSERVE,
    PERIOD,
    INCEPT,
    GRADUATE,
    CONCLUDE,
    INGRESS,
    MOVE,
    CONSTRUCT,
    DESTRUCT,
    OPERATE,
    STABLIZE,
    DESTABILIZE,
    TRANSFER,
    UTILIZE,
    DISCONTINUE,
    EGRESS,
    IMMIGRATE,
    BIRTH,
    DEATH,
    MARRIAGE,
    DIVORCE,
    EMIGRATE,
    NATURE,
    INTERACT
    ;

    public String value() {
        return name();
    }

    public static EventEnumType fromValue(String v) {
        return valueOf(v);
    }

}
