//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.26 at 09:29:53 PM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FactoryEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FactoryEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="APPROVER"/&gt;
 *     &lt;enumeration value="REQUEST"/&gt;
 *     &lt;enumeration value="APPROVAL"/&gt;
 *     &lt;enumeration value="LOCATION"/&gt;
 *     &lt;enumeration value="LOCATIONPARTICIPATION"/&gt;
 *     &lt;enumeration value="EVENT"/&gt;
 *     &lt;enumeration value="EVENTPARTICIPATION"/&gt;
 *     &lt;enumeration value="TRAIT"/&gt;
 *     &lt;enumeration value="ORGANIZATION"/&gt;
 *     &lt;enumeration value="MESSAGE"/&gt;
 *     &lt;enumeration value="SECURITYTOKEN"/&gt;
 *     &lt;enumeration value="SYMMETRICKEY"/&gt;
 *     &lt;enumeration value="ASYMMETRICKEY"/&gt;
 *     &lt;enumeration value="CONTROL"/&gt;
 *     &lt;enumeration value="ACCOUNT"/&gt;
 *     &lt;enumeration value="CREDENTIAL"/&gt;
 *     &lt;enumeration value="ADDRESS"/&gt;
 *     &lt;enumeration value="CONTACT"/&gt;
 *     &lt;enumeration value="DATA"/&gt;
 *     &lt;enumeration value="CONTACTINFORMATION"/&gt;
 *     &lt;enumeration value="CONTACTINFORMATIONPARTICIPATION"/&gt;
 *     &lt;enumeration value="GROUP"/&gt;
 *     &lt;enumeration value="DATAPARTICIPATION"/&gt;
 *     &lt;enumeration value="GROUPPARTICIPATION"/&gt;
 *     &lt;enumeration value="PERMISSION"/&gt;
 *     &lt;enumeration value="ROLE"/&gt;
 *     &lt;enumeration value="ROLEPARTICIPATION"/&gt;
 *     &lt;enumeration value="PERMISSIONPARTICIPATION"/&gt;
 *     &lt;enumeration value="TAG"/&gt;
 *     &lt;enumeration value="TAGPARTICIPATION"/&gt;
 *     &lt;enumeration value="USER"/&gt;
 *     &lt;enumeration value="STATISTICS"/&gt;
 *     &lt;enumeration value="CONTACTINFORMATION"/&gt;
 *     &lt;enumeration value="ARTIFACT"/&gt;
 *     &lt;enumeration value="BUDGET"/&gt;
 *     &lt;enumeration value="CASE"/&gt;
 *     &lt;enumeration value="CASEPARTICIPATION"/&gt;
 *     &lt;enumeration value="COST"/&gt;
 *     &lt;enumeration value="ESTIMATE"/&gt;
 *     &lt;enumeration value="FORMELEMENT"/&gt;
 *     &lt;enumeration value="FORM"/&gt;
 *     &lt;enumeration value="FORMELEMENTVALUE"/&gt;
 *     &lt;enumeration value="FORMELEMENTPARTICIPATION"/&gt;
 *     &lt;enumeration value="FORMPARTICIPATION"/&gt;
 *     &lt;enumeration value="GOAL"/&gt;
 *     &lt;enumeration value="GOALPARTICIPATION"/&gt;
 *     &lt;enumeration value="LIFECYCLE"/&gt;
 *     &lt;enumeration value="LIFECYCLEPARTICIPATION"/&gt;
 *     &lt;enumeration value="METHODOLOGY"/&gt;
 *     &lt;enumeration value="METHODOLOGYPARTICIPATION"/&gt;
 *     &lt;enumeration value="MODEL"/&gt;
 *     &lt;enumeration value="MODELPARTICIPATION"/&gt;
 *     &lt;enumeration value="MODULE"/&gt;
 *     &lt;enumeration value="MODULEPARTICIPATION"/&gt;
 *     &lt;enumeration value="NOTE"/&gt;
 *     &lt;enumeration value="PERSON"/&gt;
 *     &lt;enumeration value="PERSONPARTICIPATION"/&gt;
 *     &lt;enumeration value="PROCESS"/&gt;
 *     &lt;enumeration value="PROCESSPARTICIPATION"/&gt;
 *     &lt;enumeration value="PROCESSSTEP"/&gt;
 *     &lt;enumeration value="PROCESSSTEPPARTICIPATION"/&gt;
 *     &lt;enumeration value="PROJECT"/&gt;
 *     &lt;enumeration value="PROJECTPARTICIPATION"/&gt;
 *     &lt;enumeration value="REQUIREMENT"/&gt;
 *     &lt;enumeration value="RESOURCE"/&gt;
 *     &lt;enumeration value="SCHEDULE"/&gt;
 *     &lt;enumeration value="SCHEDULEPARTICIPATION"/&gt;
 *     &lt;enumeration value="STAGE"/&gt;
 *     &lt;enumeration value="TASK"/&gt;
 *     &lt;enumeration value="TASKPARTICIPATION"/&gt;
 *     &lt;enumeration value="TICKET"/&gt;
 *     &lt;enumeration value="TICKETPARTICIPATION"/&gt;
 *     &lt;enumeration value="TIME"/&gt;
 *     &lt;enumeration value="VALIDATIONRULE"/&gt;
 *     &lt;enumeration value="VALIDATIONRULEPARTICIPATION"/&gt;
 *     &lt;enumeration value="WORK"/&gt;
 *     &lt;enumeration value="WORKPARTICIPATION"/&gt;
 *     &lt;enumeration value="FACT"/&gt;
 *     &lt;enumeration value="FUNCTION"/&gt;
 *     &lt;enumeration value="FUNCTIONPARTICIPATION"/&gt;
 *     &lt;enumeration value="FUNCTIONFACT"/&gt;
 *     &lt;enumeration value="OPERATION"/&gt;
 *     &lt;enumeration value="PATTERN"/&gt;
 *     &lt;enumeration value="POLICY"/&gt;
 *     &lt;enumeration value="POLICYPARTICIPATION"/&gt;
 *     &lt;enumeration value="RULE"/&gt;
 *     &lt;enumeration value="RULEPARTICIPATION"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FactoryEnumType", namespace = "http://www.cote.org/accountmanager/objects/types")
@XmlEnum
public enum FactoryEnumType {

    UNKNOWN,
    APPROVER,
    REQUEST,
    APPROVAL,
    LOCATION,
    LOCATIONPARTICIPATION,
    EVENT,
    EVENTPARTICIPATION,
    TRAIT,
    ORGANIZATION,
    MESSAGE,
    SECURITYTOKEN,
    SYMMETRICKEY,
    ASYMMETRICKEY,
    CONTROL,
    ACCOUNT,
    CREDENTIAL,
    ADDRESS,
    CONTACT,
    DATA,
    CONTACTINFORMATION,
    CONTACTINFORMATIONPARTICIPATION,
    GROUP,
    DATAPARTICIPATION,
    GROUPPARTICIPATION,
    PERMISSION,
    ROLE,
    ROLEPARTICIPATION,
    PERMISSIONPARTICIPATION,
    TAG,
    TAGPARTICIPATION,
    USER,
    STATISTICS,
    ARTIFACT,
    BUDGET,
    CASE,
    CASEPARTICIPATION,
    COST,
    ESTIMATE,
    FORMELEMENT,
    FORM,
    FORMELEMENTVALUE,
    FORMELEMENTPARTICIPATION,
    FORMPARTICIPATION,
    GOAL,
    GOALPARTICIPATION,
    LIFECYCLE,
    LIFECYCLEPARTICIPATION,
    METHODOLOGY,
    METHODOLOGYPARTICIPATION,
    MODEL,
    MODELPARTICIPATION,
    MODULE,
    MODULEPARTICIPATION,
    NOTE,
    PERSON,
    PERSONPARTICIPATION,
    PROCESS,
    PROCESSPARTICIPATION,
    PROCESSSTEP,
    PROCESSSTEPPARTICIPATION,
    PROJECT,
    PROJECTPARTICIPATION,
    REQUIREMENT,
    RESOURCE,
    SCHEDULE,
    SCHEDULEPARTICIPATION,
    STAGE,
    TASK,
    TASKPARTICIPATION,
    TICKET,
    TICKETPARTICIPATION,
    TIME,
    VALIDATIONRULE,
    VALIDATIONRULEPARTICIPATION,
    WORK,
    WORKPARTICIPATION,
    FACT,
    FUNCTION,
    FUNCTIONPARTICIPATION,
    FUNCTIONFACT,
    OPERATION,
    PATTERN,
    POLICY,
    POLICYPARTICIPATION,
    RULE,
    RULEPARTICIPATION;

    public String value() {
        return name();
    }

    public static FactoryEnumType fromValue(String v) {
        return valueOf(v);
    }

}
