//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.26 at 09:29:53 PM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FactEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FactEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="GROUP"/&gt;
 *     &lt;enumeration value="ROLE"/&gt;
 *     &lt;enumeration value="PERMISSION"/&gt;
 *     &lt;enumeration value="PROPERTY"/&gt;
 *     &lt;enumeration value="ATTRIBUTE"/&gt;
 *     &lt;enumeration value="STATIC"/&gt;
 *     &lt;enumeration value="FACTORY"/&gt;
 *     &lt;enumeration value="REST"/&gt;
 *     &lt;enumeration value="FUNCTION"/&gt;
 *     &lt;enumeration value="SUBJECT"/&gt;
 *     &lt;enumeration value="CONTEXT"/&gt;
 *     &lt;enumeration value="PARAMETER"/&gt;
 *     &lt;enumeration value="OPERATION"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FactEnumType")
@XmlEnum
public enum FactEnumType {

    UNKNOWN,
    GROUP,
    ROLE,
    PERMISSION,
    PROPERTY,
    ATTRIBUTE,
    STATIC,
    FACTORY,
    REST,
    FUNCTION,
    SUBJECT,
    CONTEXT,
    PARAMETER,
    OPERATION;

    public String value() {
        return name();
    }

    public static FactEnumType fromValue(String v) {
        return valueOf(v);
    }

}
