//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.26 at 09:29:53 PM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatternEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PatternEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="PARAMETER"/&gt;
 *     &lt;enumeration value="FUNCTION"/&gt;
 *     &lt;enumeration value="OPERATION"/&gt;
 *     &lt;enumeration value="EXPRESSION"/&gt;
 *     &lt;enumeration value="AUTHORIZATION"/&gt;
 *     &lt;enumeration value="SEPARATION_OF_DUTY"/&gt;
 *     &lt;enumeration value="VERIFICATION"/&gt;
 *     &lt;enumeration value="APPROVAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PatternEnumType")
@XmlEnum
public enum PatternEnumType {

    UNKNOWN,
    PARAMETER,
    FUNCTION,
    OPERATION,
    EXPRESSION,
    AUTHORIZATION,
    SEPARATION_OF_DUTY,
    VERIFICATION,
    APPROVAL;

    public String value() {
        return name();
    }

    public static PatternEnumType fromValue(String v) {
        return valueOf(v);
    }

}
