//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.26 at 09:29:53 PM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyResponseEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PolicyResponseEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="AUTHENTICATED"/&gt;
 *     &lt;enumeration value="PERMIT"/&gt;
 *     &lt;enumeration value="DENY"/&gt;
 *     &lt;enumeration value="PENDING"/&gt;
 *     &lt;enumeration value="PENDING_OPERATION"/&gt;
 *     &lt;enumeration value="INVALID_ARGUMENT"/&gt;
 *     &lt;enumeration value="ERROR"/&gt;
 *     &lt;enumeration value="BANNED"/&gt;
 *     &lt;enumeration value="DISABLED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PolicyResponseEnumType")
@XmlEnum
public enum PolicyResponseEnumType {

    UNKNOWN,
    AUTHENTICATED,
    PERMIT,
    DENY,
    PENDING,
    PENDING_OPERATION,
    INVALID_ARGUMENT,
    ERROR,
    BANNED,
    DISABLED;

    public String value() {
        return name();
    }

    public static PolicyResponseEnumType fromValue(String v) {
        return valueOf(v);
    }

}
