//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.27 at 10:38:29 AM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpoolNameEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpoolNameEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="GENERAL"/&gt;
 *     &lt;enumeration value="AUTHORIZATION"/&gt;
 *     &lt;enumeration value="STATE"/&gt;
 *     &lt;enumeration value="MESSAGE"/&gt;
 *     &lt;enumeration value="QUEUE"/&gt;
 *     &lt;enumeration value="DATA"/&gt;
 *     &lt;enumeration value="REQUEST"/&gt;
 *     &lt;enumeration value="ACCESS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SpoolNameEnumType", namespace = "http://www.cote.org/accountmanager/objects/types")
@XmlEnum
public enum SpoolNameEnumType {

    UNKNOWN,
    GENERAL,
    AUTHORIZATION,
    STATE,
    MESSAGE,
    QUEUE,
    DATA,
    REQUEST,
    ACCESS;

    public String value() {
        return name();
    }

    public static SpoolNameEnumType fromValue(String v) {
        return valueOf(v);
    }

}
