//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.27 at 10:38:29 AM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpoolStatusEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpoolStatusEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="ERROR"/&gt;
 *     &lt;enumeration value="QUEUEING"/&gt;
 *     &lt;enumeration value="QUEUED"/&gt;
 *     &lt;enumeration value="TRANSMITTING"/&gt;
 *     &lt;enumeration value="TRANSMITTED"/&gt;
 *     &lt;enumeration value="SPOOLING"/&gt;
 *     &lt;enumeration value="SPOOLED"/&gt;
 *     &lt;enumeration value="ACKNOWLEGED_RECEIPT"/&gt;
 *     &lt;enumeration value="RESPONDED"/&gt;
 *     &lt;enumeration value="PERSISTED"/&gt;
 *     &lt;enumeration value="REJECTED"/&gt;
 *     &lt;enumeration value="DELETED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SpoolStatusEnumType", namespace = "http://www.cote.org/accountmanager/objects/types")
@XmlEnum
public enum SpoolStatusEnumType {

    UNKNOWN,
    ERROR,
    QUEUEING,
    QUEUED,
    TRANSMITTING,
    TRANSMITTED,
    SPOOLING,
    SPOOLED,
    ACKNOWLEGED_RECEIPT,
    RESPONDED,
    PERSISTED,
    REJECTED,
    DELETED;

    public String value() {
        return name();
    }

    public static SpoolStatusEnumType fromValue(String v) {
        return valueOf(v);
    }

}
