//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.22 at 05:13:20 PM CDT 
//


package org.cote.accountmanager.schema.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "TraitEnumType", namespace = "http://www.cote.org/propellant/objects/types")
@XmlEnum
public enum TraitEnumType {

    UNKNOWN,
    FEATURE,
    PERK,
    SKILL,
    RESOURCE,
    LOCATION,
    TRANSPORT,
    PROTOCOL,
    EVENT,
    PERSON;

    public String value() {
        return name();
    }

    public static TraitEnumType fromValue(String v) {
        return valueOf(v);
    }

}
