package org.cote.accountmanager.olio;

public enum ThreatEnumType {
	ANIMAL_TARGET,
	ANIMAL_THREAT,
	ECONOMIC_TARGET,
	ECONOMIC_THREAT,
	ENVIRONMENTAL_THREAT,
	EXISTENTIAL_THREAT,
	EXISTENTIAL_TARGET,
	HEALTH_TARGET,
	HEALTH_THREAT,
	HOLLOW_THREAT,
	IDEOLOGICAL_TARGET,
	IDEOLOGICAL_THREAT,
	NONE,
	PERSONAL_TARGET,
	PERSONAL_THREAT,
	PHYSICAL_TARGET,
	PHYSICAL_THREAT,
	POLITICAL_TARGET,
	POLITICAL_THREAT,
	PSYCHOLOGICAL_TARGET,
	PSYCHOLOGICAL_THREAT,
	SOCIAL_TARGET,
	SOCIAL_THREAT,
	VERBAL_TARGET,
	VERBAL_THREAT;

	public static ThreatEnumType[] getThreats() {
		return new ThreatEnumType[] {
			ANIMAL_THREAT, ECONOMIC_THREAT, ENVIRONMENTAL_THREAT, EXISTENTIAL_THREAT, HEALTH_THREAT,
			IDEOLOGICAL_THREAT, PERSONAL_THREAT, PHYSICAL_THREAT, POLITICAL_THREAT, PSYCHOLOGICAL_THREAT,
			SOCIAL_THREAT, VERBAL_THREAT, HOLLOW_THREAT
		};
	}
	
	public static ThreatEnumType[] getTargets() {
		return new ThreatEnumType[] {
			ANIMAL_TARGET, ECONOMIC_TARGET, EXISTENTIAL_TARGET, HEALTH_TARGET,
			IDEOLOGICAL_TARGET, PERSONAL_TARGET, PHYSICAL_TARGET, POLITICAL_TARGET, PSYCHOLOGICAL_TARGET,
			SOCIAL_TARGET, VERBAL_TARGET
		};
	}
	
	public static ThreatEnumType getTarget(ThreatEnumType threat) {
		ThreatEnumType tet = ThreatEnumType.NONE;
		switch(threat) {
		
		case ANIMAL_THREAT:
			tet = ANIMAL_TARGET;
			break;
		case ECONOMIC_THREAT:
			tet = ECONOMIC_TARGET;
			break;
		case ENVIRONMENTAL_THREAT:
			tet = PHYSICAL_TARGET;
			break;
		case EXISTENTIAL_THREAT:
			tet = EXISTENTIAL_TARGET;
			break;
		case HEALTH_THREAT: 
			tet = HEALTH_TARGET;
			break;
		case HOLLOW_THREAT:
			tet = PSYCHOLOGICAL_TARGET;
			break;
		case IDEOLOGICAL_THREAT:
			tet = IDEOLOGICAL_TARGET;
			break;
		case PERSONAL_THREAT:
			tet = PERSONAL_TARGET;
			break;
		case PHYSICAL_THREAT:
			tet = PHYSICAL_TARGET;
			break;
		case POLITICAL_THREAT:
			tet = POLITICAL_TARGET;
			break;
		case PSYCHOLOGICAL_THREAT:
			tet = PSYCHOLOGICAL_TARGET;
			break;
		case SOCIAL_THREAT: 
			tet = SOCIAL_TARGET;
			break;
		case VERBAL_THREAT: 
			tet = VERBAL_TARGET;
			break;
		default:
			tet = NONE;
		}
		return tet;
	}
	
}
