package org.cote.accountmanager.olio;

public enum ThreatEnumType {
	NONE,
	EXISTENTIAL_THREAT,
	ANIMAL_THREAT,
	ANIMAL_TARGET,
	PERSONAL_THREAT,
	PERSONAL_TARGET,
	ECONOMIC_THREAT,
	ECONOMIC_TARGET,
	IDEOLOGICAL_THREAT,
	IDEOLOGICAL_TARGET,
	ENVIRONMENTAL_THREAT,
	HEALTH_THREAT,
	POLITICAL_THREAT,
	POLITICAL_TARGET
	/*
	ENVIRONMENTAL_SECURITY,
	ECONOMIC_SECURITY,
	FOOD_SECURITY,
	HEALTH_SECURITY,
	PERSONAL_SECURITY,
	COMMUNITY_SECURITY,
	POLITICAL_SECURITY
	*/
};
