package org.cote.accountmanager.objects.tests;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import static org.junit.Assume.assumeTrue;

import java.util.ArrayList;
import java.util.List;

import org.cote.accountmanager.io.IOSystem;
import org.cote.accountmanager.io.OrganizationContext;
import org.cote.accountmanager.io.ParameterList;
import org.cote.accountmanager.io.Query;
import org.cote.accountmanager.io.QueryUtil;
import org.cote.accountmanager.objects.tests.olio.OlioTestUtil;
import org.cote.accountmanager.olio.picturebook.ChapBookUtil;
import org.cote.accountmanager.olio.picturebook.PbBookUtil;
import org.cote.accountmanager.olio.picturebook.PictureBookException;
import org.cote.accountmanager.olio.schema.OlioFieldNames;
import org.cote.accountmanager.olio.schema.OlioModelNames;
import org.cote.accountmanager.record.BaseRecord;
import org.cote.accountmanager.schema.FieldNames;
import org.junit.Before;
import org.junit.Test;

/**
 * Integration tests for the human-edited ChapBook landscape prompt feature:
 * {@link ChapBookUtil#setSceneLandscapePrompt(BaseRecord, String, String)} and the 7-arg
 * {@link ChapBookUtil#renderChapBookScene(BaseRecord, String, String, String, BaseRecord, BaseRecord, String)}
 * {@code promptOverride} overload.
 * <p>
 * Live integration tests against the real DB (test 1) and, gated, the live SD server (test 2). Nothing
 * is mocked. A non-admin {@code getCreateUser} user is used throughout; the admin user only provisions it.
 * <ol>
 *   <li><b>Persist-verbatim + read-back (PURE PERSISTENCE — no LLM, no SD; runs unconditionally).</b>
 *       {@code setSceneLandscapePrompt} persists the value EXACTLY (no {@code "landscape, "} discriminator
 *       rewriting), including a fallback-shaped human edit; a blank value CLEARS the field; a bogus scene
 *       objectId throws {@link PictureBookException} 404.</li>
 *   <li><b>Render honors promptOverride VERBATIM (gated on SD).</b> The 7-arg
 *       {@code renderChapBookScene} with a fallback-shaped override renders (RENDERED + non-null
 *       imageObjectId) and leaves the scene's stored {@code sdPrompt} EXACTLY the override — proving the
 *       override drove the render, was persisted, and was NOT regenerated by the LLM despite its
 *       {@code "landscape, "} shape (a live, regeneration-capable chatConfig is supplied and yet the
 *       verbatim edit wins).</li>
 * </ol>
 */
public class TestChapBookSceneLandscapePrompt extends BaseTest {

	private static final String ORG_PATH = "/Development/ChapBook Tests";

	/** REAL two-stanza poem corpus (verbatim from {@link TestChapBookRenderSignal}). */
	private static final String POEM_TEXT =
		"Outside, all is pristine,\n" +
		"From cobalt skies of charcoal unity\n" +
		"Descending upon snow canvassed green\n" +
		"To silver veins of icy sheens,\n" +
		"Born of spells and sorcery.\n" +
		"\n" +
		"Inside hearts and hearths and homes,\n" +
		"Ochre embers and ebon cinders,\n" +
		"Faded life stirred by motherly crones,\n" +
		"Dry damp clothes and warm cold bones\n" +
		"And illuminate the age-old spellbound tomes.";

	private BaseRecord testUser;
	private long orgId;

	@Before
	public void setUpLandscapePrompt() {
		// BaseTest.setup() (@Before) runs first and calls OlioModelNames.use(). Reuse the ChapBook suite's
		// stable NON-ADMIN test user (admin only provisions it via getCreateUser).
		OrganizationContext ctx = getTestOrganization(ORG_PATH);
		testUser = IOSystem.getActiveContext().getFactory()
			.getCreateUser(ctx.getAdminUser(), "chapbookLandscapePromptUser", ctx.getOrganizationId());
		assertNotNull("chapbookLandscapePromptUser must be created", testUser);
		orgId = ((Number) testUser.get(FieldNames.FIELD_ORGANIZATION_ID)).longValue();
	}

	/**
	 * PURE PERSISTENCE (no LLM, no SD) — must run unconditionally.
	 * <p>
	 * Builds a ChapBook with {@code chatConfig == null} so scenes exist purely from persistence, then
	 * proves the {@code setSceneLandscapePrompt} contract end to end against the live DB:
	 * <ol>
	 *   <li>an ordinary human edit persists VERBATIM and reads back exactly;</li>
	 *   <li>a fallback-SHAPED human edit ({@code "landscape, ..."}) is stored VERBATIM too — the
	 *       {@code "landscape, "} discriminator must NOT strip or rewrite a deliberate human edit;</li>
	 *   <li>a blank value CLEARS the field (persists null);</li>
	 *   <li>a bogus scene objectId throws {@link PictureBookException} with status 404.</li>
	 * </ol>
	 */
	@Test
	public void testSetSceneLandscapePromptPersistsVerbatimAndClears() {
		String dataPath = testProperties.getProperty("test.datagen.path");
		assertNotNull("test.datagen.path must be set", dataPath);
		long ts = System.currentTimeMillis();

		BaseRecord poem = createPoem(testUser, "~/Data/ChapBookLandscapePersist-" + ts,
			"Poem Landscape Persist " + ts, POEM_TEXT);
		assertNotNull("Poem must be created", poem);
		List<String> poemOids = new ArrayList<>();
		poemOids.add(poem.get(FieldNames.FIELD_OBJECT_ID));

		// No chatConfig at create → scenes exist purely from persistence (no LLM).
		BaseRecord book = ChapBookUtil.createChapBook(testUser, dataPath, "cb-lsprompt-persist-" + ts,
			"ChapBook Landscape Persist " + ts, poemOids, 5, null);
		assertNotNull("createChapBook must return a book", book);
		BaseRecord bookCheck = reloadBook(book);
		List<BaseRecord> scenes = PbBookUtil.listScenes(testUser, bookCheck);
		assertFalse("At least one scene must be created", scenes.isEmpty());
		String sceneOid = scenes.get(0).get(FieldNames.FIELD_OBJECT_ID);
		assertNotNull("Scene must carry an objectId", sceneOid);

		// ── 1. Ordinary human edit → persisted VERBATIM ──
		String plainEdit = "a serene alpine meadow at dawn, wildflowers, soft mist";
		assertTrue("setSceneLandscapePrompt must return true on a successful update",
			ChapBookUtil.setSceneLandscapePrompt(testUser, sceneOid, plainEdit));
		assertEquals("A human-edited landscape prompt must persist VERBATIM and read back exactly",
			plainEdit, readSdPromptFresh(sceneOid));

		// ── 2. Fallback-SHAPED human edit → still VERBATIM (discriminator must NOT rewrite it) ──
		String fallbackShaped = "landscape, a human edit that happens to start this way";
		assertTrue("setSceneLandscapePrompt must return true for a fallback-shaped human edit",
			ChapBookUtil.setSceneLandscapePrompt(testUser, sceneOid, fallbackShaped));
		assertEquals("A fallback-shaped ('landscape, ') human edit must be stored VERBATIM — the "
			+ "discriminator must NOT strip/alter a deliberate human edit",
			fallbackShaped, readSdPromptFresh(sceneOid));

		// ── 3. Blank value → CLEARS the field (persists null) ──
		assertTrue("setSceneLandscapePrompt with a blank value must return true (a successful CLEAR)",
			ChapBookUtil.setSceneLandscapePrompt(testUser, sceneOid, ""));
		String cleared = readSdPromptFresh(sceneOid);
		assertTrue("A blank value must CLEAR the stored sdPrompt (null/blank), got: " + cleared,
			cleared == null || cleared.isBlank());

		// ── 4. Bogus scene objectId → PictureBookException 404 ──
		try {
			ChapBookUtil.setSceneLandscapePrompt(testUser, "no-such-scene-" + ts, "anything");
			fail("setSceneLandscapePrompt on a bogus scene objectId must throw PictureBookException 404");
		} catch (PictureBookException pbe) {
			assertEquals("Missing scene must throw PictureBookException with status 404", 404, pbe.getStatus());
		}

		logger.info("setSceneLandscapePrompt: verbatim + fallback-shaped + clear + 404 all verified (scene {})", sceneOid);
	}

	/**
	 * Render honors {@code promptOverride} VERBATIM. Gated on {@code test.swarm.server} (the render needs
	 * a live SD server at 192.168.1.39, reachable from the HOST). If SD is genuinely unreachable the test
	 * SKIPS via {@link org.junit.Assume} — it never fakes a pass.
	 * <p>
	 * A LIVE, regeneration-capable {@code chatConfig} is supplied AND the override is fallback-SHAPED
	 * ({@code "landscape, ..."}). If the code misclassified the override as the no-LLM fallback it would run
	 * the LLM recovery and store a DIFFERENT prompt; the exact-match assertion below would then fail. So a
	 * pass proves the override short-circuits the stored-vs-LLM resolution and is honored verbatim.
	 */
	@Test
	public void testRenderHonorsPromptOverrideVerbatim() {
		String swarmServer = testProperties.getProperty("test.swarm.server");
		assumeTrue("test.swarm.server not configured — skipping ChapBook render override test",
			swarmServer != null && !swarmServer.isBlank());
		String llmServer = testProperties.getProperty("test.llm.ollama.server");
		assumeTrue("test.llm.ollama.server not configured — skipping ChapBook render override test",
			llmServer != null && !llmServer.isBlank());

		String dataPath = testProperties.getProperty("test.datagen.path");
		assertNotNull("test.datagen.path must be set", dataPath);
		long ts = System.currentTimeMillis();

		// A live, regeneration-CAPABLE chatConfig. It is deliberately supplied so that IF the override were
		// misclassified as the no-LLM fallback, recovery WOULD run and overwrite the stored prompt. The
		// verbatim override short-circuits resolveScenePrompt, so the LLM is in fact never contacted.
		BaseRecord liveConfig = OlioTestUtil.getOllamaOpenAIConfig(testUser, "chapbookOverrideLlmConfig", testProperties);
		assertNotNull("Live chatConfig must be built", liveConfig);

		BaseRecord poem = createPoem(testUser, "~/Data/ChapBookLandscapeRender-" + ts,
			"Poem Landscape Render " + ts, POEM_TEXT);
		assertNotNull("Poem must be created", poem);
		List<String> poemOids = new ArrayList<>();
		poemOids.add(poem.get(FieldNames.FIELD_OBJECT_ID));

		// No chatConfig at create → scenes carry the fallback-shaped stored prompt, so the override is
		// genuinely competing against the fallback discriminator at render time.
		BaseRecord book = ChapBookUtil.createChapBook(testUser, dataPath, "cb-lsprompt-render-" + ts,
			"ChapBook Landscape Render " + ts, poemOids, 5, null);
		assertNotNull("createChapBook must return a book", book);
		BaseRecord bookCheck = reloadBook(book);
		List<BaseRecord> scenes = PbBookUtil.listScenes(testUser, bookCheck);
		assertFalse("At least one scene must be created", scenes.isEmpty());
		String sceneOid = scenes.get(0).get(FieldNames.FIELD_OBJECT_ID);

		String override = "landscape, a lone lighthouse on a stormy cliff";

		ChapBookUtil.SceneRenderResult result = ChapBookUtil.renderChapBookScene(
			testUser, sceneOid, "SWARM", swarmServer, liveConfig, null, override);

		assertNotNull("renderChapBookScene must return a result", result);
		// (a) The override drove a real render.
		assertEquals("A promptOverride render with live SD must produce a RENDERED result",
			ChapBookUtil.SceneRenderStatus.RENDERED, result.status);
		assertNotNull("A RENDERED result must carry an imageObjectId", result.imageObjectId);
		assertFalse("imageObjectId must be non-blank", result.imageObjectId.isBlank());

		// (b) The scene's stored prompt re-reads as the EXACT override — persisted and NOT regenerated by
		// the LLM despite the "landscape, " shape (a live chatConfig capable of regeneration was supplied).
		String stored = readSdPromptFresh(sceneOid);
		assertEquals("The scene's stored sdPrompt must equal the override VERBATIM — proving it drove the "
			+ "render, was persisted, and was NOT regenerated by the LLM despite its 'landscape, ' shape",
			override, stored);

		logger.info("renderChapBookScene override: scene {} RENDERED image={}, stored sdPrompt verbatim='{}'",
			sceneOid, result.imageObjectId, stored);
	}

	// ── helpers ──────────────────────────────────────────────────────────────

	/** Fresh (cache-bypassing) read of a scene's stored landscape prompt via the projected read path. */
	private String readSdPromptFresh(String sceneObjectId) {
		BaseRecord scene = PbBookUtil.readScene(testUser, sceneObjectId, orgId);
		assertNotNull("Scene must be re-readable by objectId " + sceneObjectId, scene);
		return scene.get(OlioFieldNames.FIELD_CB_SD_PROMPT);
	}

	/** Re-load a freshly-created book by objectId with the fields {@code listScenes} needs. */
	private BaseRecord reloadBook(BaseRecord book) {
		String bookObjectId = book.get(FieldNames.FIELD_OBJECT_ID);
		assertNotNull("Book must have an objectId", bookObjectId);
		Query bq = QueryUtil.createQuery(OlioModelNames.MODEL_PB_BOOK, FieldNames.FIELD_OBJECT_ID, bookObjectId);
		bq.field(FieldNames.FIELD_ORGANIZATION_ID, orgId);
		bq.setRequest(new String[]{
			FieldNames.FIELD_ID, FieldNames.FIELD_OBJECT_ID, FieldNames.FIELD_NAME,
			FieldNames.FIELD_GROUP_ID, FieldNames.FIELD_GROUP_PATH, FieldNames.FIELD_ORGANIZATION_ID,
			FieldNames.FIELD_OWNER_ID, OlioFieldNames.FIELD_PB_BOOK_TYPE
		});
		bq.setCache(false);
		BaseRecord bookCheck = IOSystem.getActiveContext().getAccessPoint().find(testUser, bq);
		assertNotNull("Book must be findable by objectId", bookCheck);
		return bookCheck;
	}

	/** Create an {@code olio.cb.poem} at the given path (identity-only record returned). */
	private BaseRecord createPoem(BaseRecord user, String groupPath, String name, String text) {
		try {
			ParameterList plist = ParameterList.newParameterList(FieldNames.FIELD_PATH, groupPath);
			plist.parameter(FieldNames.FIELD_NAME, name);
			BaseRecord poem = IOSystem.getActiveContext().getFactory()
				.newInstance(OlioModelNames.MODEL_CB_POEM, user, null, plist);
			poem.set("text", text);
			poem.set("title", name);
			return IOSystem.getActiveContext().getAccessPoint().create(user, poem);
		} catch (Exception e) {
			logger.error("createPoem failed: {}", e.getMessage(), e);
			return null;
		}
	}
}
